import { useState, useEffect, useCallback } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { BookOpen, DollarSign, Sparkles, Loader2, Settings } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import { useAuth } from "@/hooks/useAuth";
import { TitlePreferencesModal } from "./TitlePreferencesModal";
import { EbayAuthModal } from "./EbayAuthModal";
import type { InventoryItem } from "@/types/inventory";


interface CreateListingModalProps {
  item: InventoryItem | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export function CreateListingModal({ item, open, onOpenChange }: CreateListingModalProps) {
  const { toast } = useToast();
  const { user } = useAuth();
  const [isGeneratingListing, setIsGeneratingListing] = useState(false);
  const [showPreferences, setShowPreferences] = useState(false);
  const [showEbayAuth, setShowEbayAuth] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const [ebayTokenValid, setEbayTokenValid] = useState<boolean | null>(null);
  const [listingData, setListingData] = useState({
    title: item?.title || item?.suggested_title || "",
    price: item?.suggested_price?.toString() || "",
    description: item?.author ? `By ${item?.author}${item?.publisher ? ` - ${item?.publisher}` : ''}${item?.publication_year ? ` (${item?.publication_year})` : ''}` : "",
    condition: item?.condition_assessment || "good",
    category: item?.suggested_category || (item?.genre?.toLowerCase().includes('magazine') ? 'magazine' : 'book'),
    genre: item?.genre || "",
    topic: item?.topic || ""
  });

  // Check eBay token status when modal opens
  const checkEbayTokenStatus = useCallback(async () => {
    try {
      const { data: tokens, error } = await supabase
        .from('oauth_tokens')
        .select('access_token, expires_at')
        .eq('user_id', user?.id)
        .eq('provider', 'ebay')
        .single();

      if (error || !tokens?.access_token) {
        setEbayTokenValid(false);
        return;
      }

      // Check if token is expired (expires within next 5 minutes)
      const expiresAt = new Date(tokens.expires_at);
      const now = new Date();
      const fiveMinutesFromNow = new Date(now.getTime() + 5 * 60 * 1000);

      if (expiresAt <= fiveMinutesFromNow) {
        setEbayTokenValid(false);
        return;
      }

      setEbayTokenValid(true);
    } catch (error) {
      console.error('Error checking eBay token:', error);
      setEbayTokenValid(false);
    }
  }, [user]);

  useEffect(() => {
    if (open && user) {
      checkEbayTokenStatus();
    }
    if (!open) {
      setHasAutoGenerated(false);
      setEbayTokenValid(null);
    }
  }, [open, user, checkEbayTokenStatus]);

  const generateOptimizedListing = useCallback(async () => {
    if (!item) return;

    setIsGeneratingListing(true);
    try {
      const { data, error } = await supabase.functions.invoke('generate-ebay-listing', {
        body: {
          itemData: {
            title: item.title,
            author: item.author,
            publisher: item.publisher,
            publication_year: item.publication_year,
            condition: item.condition_assessment || 'good',
            category: item.suggested_category || 'book',
            isbn: item.isbn,
            genre: item.genre,
            issue_number: item.issue_number,
            issue_date: item.issue_date,
            issue_title: item.subtitle,
            topic: item.topic
          },
          userId: user?.id
        }
      });

      if (error) {
        throw new Error(error.message);
      }

      if (data?.success && data?.optimizedListing) {
        // Handle both string and object responses from the AI
        let title = data.optimizedListing.title;
        let description = data.optimizedListing.description;
        let price = data.optimizedListing.price || item?.suggested_price || 0;

        // If the response contains JSON markup, extract and parse it
        if (typeof data.optimizedListing.description === 'string') {
          let jsonString = data.optimizedListing.description.trim();

          // Remove markdown code block if present
          if (jsonString.startsWith('```json')) {
            jsonString = jsonString.replace(/^```json\s*/, '').replace(/\s*```$/, '');
          }

          // Try to parse as JSON
          if (jsonString.startsWith('{')) {
            try {
              const parsed = JSON.parse(jsonString);
              title = parsed.title || title;
              description = parsed.description || description;
              price = parsed.price || price;
            } catch (e) {
              console.warn('Failed to parse JSON description, using as-is');
              // If parsing fails, use the original description without the JSON markup
              description = data.optimizedListing.description.replace(/^```json\s*/, '').replace(/\s*```$/, '');
            }
          }
        }

        setListingData(prev => ({
          ...prev,
          title: title,
          description: description,
          price: price?.toString() || prev.price
        }));

        toast({
          title: "Listing Generated!",
          description: `SEO-optimized title, description, and pricing have been generated. Price: $${price}`,
        });
      } else {
        throw new Error('Failed to generate optimized listing');
      }
    } catch (error) {
      console.error('Error generating listing:', error);

      // Check if it's an eBay authentication error
      if (error.message?.includes('invalid scopes') || error.message?.includes('auth')) {
        toast({
          title: "eBay Authentication Required",
          description: "Please connect your eBay account with the required scopes.",
          variant: "destructive",
        });
        setShowEbayAuth(true);
      } else {
        toast({
          title: "Generation Failed",
          description: `Pricing generation error: ${error.message || "Could not generate optimized listing. Please try again."}`,
          variant: "destructive",
        });
      }
    } finally {
      setIsGeneratingListing(false);
    }
  }, [item, user, toast]);

  // Auto-generate title and price when modal opens if they're empty
  useEffect(() => {
    if (open && item && !hasAutoGenerated && ebayTokenValid) {
      const needsTitle = !listingData.title || listingData.title === "";
      const needsPrice = !listingData.price || listingData.price === "0" || listingData.price === "";

      if (needsTitle || needsPrice) {
        generateOptimizedListing();
        setHasAutoGenerated(true);
      }
    }
  }, [
    open,
    item,
    ebayTokenValid,
    generateOptimizedListing,
    hasAutoGenerated,
    listingData.title,
    listingData.price,
  ]);

  // Reset state when item changes
  useEffect(() => {
    if (item) {
      setListingData({
        title: item?.title || item?.suggested_title || "",
        price: item?.suggested_price?.toString() || "",
        description: item?.author ? `By ${item?.author}${item?.publisher ? ` - ${item?.publisher}` : ''}${item?.publication_year ? ` (${item?.publication_year})` : ''}` : "",
        condition: item?.condition_assessment || "good",
        category: item?.suggested_category || (item?.genre?.toLowerCase().includes('magazine') ? 'magazine' : 'book'),
        genre: item?.genre || "",
        topic: item?.topic || ""
      });
      setHasAutoGenerated(false);
    }
  }, [item]);

  const categoryMapping = {
    book: "267",
    magazine: "280",
    other: "267"
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!item) return;

    // Pre-flight checks
    if (!user) {
      toast({
        title: "Authentication Required",
        description: "Please sign in to create listings.",
        variant: "destructive",
      });
      return;
    }

    if (ebayTokenValid === false) {
      toast({
        title: "eBay Authentication Required",
        description: "Please connect your eBay account to create listings.",
        variant: "destructive",
      });
      setShowEbayAuth(true);
      return;
    }
    
    setIsGeneratingListing(true);
    try {
      console.log('Creating eBay listing for item:', item?.id, 'with data:', listingData);
      
      // Create the actual eBay listing
      const { data, error } = await supabase.functions.invoke('ebay-create-listing', {
        body: {
          itemId: item.id,
          listingData: {
            title: listingData.title,
            description: listingData.description,
            price: parseFloat(listingData.price),
            condition: listingData.condition,
            categoryId: categoryMapping[listingData.category] || "267",
            isbn: item.isbn,
            author: item.author
          }
        }
      });

      if (error) {
        throw new Error(error.message);
      }

      if (!data?.success) {
        throw new Error(data?.error || 'Failed to create eBay listing');
      }

      toast({
        title: "Listing Created Successfully!",
        description: `Your item has been listed on eBay. Listing ID: ${data.listingId}`,
      });
      
      // Force refresh the inventory list
      window.dispatchEvent(new CustomEvent('inventoryRefresh'));
      
      onOpenChange(false);
    } catch (error) {
      console.error('Error creating eBay listing:', error);
      
      // Check if it's an eBay authentication error
      if (error.message?.includes('authentication') || error.message?.includes('token') || error.message?.includes('unauthorized')) {
        toast({
          title: "eBay Authentication Required",
          description: "Please reconnect your eBay account to create listings.",
          variant: "destructive",
        });
        setEbayTokenValid(false);
        setShowEbayAuth(true);
      } else {
        let errorMessage = error.message || "Failed to create eBay listing. Please try again.";
        
        // Surface specific eBay API errors more clearly
        if (errorMessage.includes('Accept-Language')) {
          errorMessage = "eBay API language header issue. Please try again.";
        } else if (errorMessage.includes('token') || errorMessage.includes('expired')) {
          errorMessage = "eBay authentication expired. Please reconnect your eBay account.";
        } else if (errorMessage.includes('category')) {
          errorMessage = "Invalid eBay category. Please check the item type.";
        }
        
        toast({
          title: "Listing Creation Failed",
          description: errorMessage,
          variant: "destructive",
        });
        console.error('eBay listing creation error details:', error);
      }
    } finally {
      setIsGeneratingListing(false);
    }
  };

  if (!item) return null;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Create eBay Listing</DialogTitle>
          <DialogDescription>
            Create an eBay listing for this item with optimized details and pricing.
          </DialogDescription>
        </DialogHeader>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {/* Item Preview */}
          <div className="space-y-4">
            <div className="aspect-[3/4] bg-muted rounded-lg flex items-center justify-center overflow-hidden">
          {Array.isArray(item.photos) ? item.photos[0]?.public_url : item.photos?.public_url ? (
            <img 
              src={Array.isArray(item.photos) ? item.photos[0]?.public_url : item.photos?.public_url}
                  alt={item.title || 'Item photo'}
                  className="w-full h-full object-cover"
                />
              ) : (
                <BookOpen className="w-8 h-8 text-muted-foreground" />
              )}
            </div>
            
            <div className="space-y-2">
              <h3 className="font-medium">Original Details</h3>
              <p className="text-sm text-muted-foreground">
                <strong>Title:</strong> {item.title || 'Unknown'}
              </p>
              <p className="text-sm text-muted-foreground">
                <strong>Author:</strong> {item.author || 'Unknown'}
              </p>
              <p className="text-sm text-muted-foreground">
                <strong>Suggested Price:</strong> ${item.suggested_price?.toFixed(2) || '0.00'}
              </p>
              <div className="flex items-center gap-2">
                <Badge variant="outline">{item.suggested_category}</Badge>
                <Badge variant="outline" className="bg-success/10 text-success border-success/20">
                  {item.confidence_score || 0}% confidence
                </Badge>
              </div>
            </div>
          </div>

          {/* Listing Form */}
          <form onSubmit={handleSubmit} className="space-y-4">
            <div className="flex justify-between items-center">
              <h3 className="font-medium">Listing Details</h3>
              <div className="flex gap-2">
                <Button 
                  type="button" 
                  variant="ghost" 
                  size="sm"
                  onClick={() => setShowPreferences(true)}
                  title="Set global title prefixes, suffixes, and custom text"
                >
                  <Settings className="w-4 h-4" />
                </Button>
                <Button 
                  type="button" 
                  variant="outline" 
                  size="sm"
                  onClick={generateOptimizedListing}
                  disabled={isGeneratingListing}
                  title="Generate SEO-optimized title and description with your preferences"
                >
                  {isGeneratingListing ? (
                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  ) : (
                    <Sparkles className="w-4 h-4 mr-2" />
                  )}
                  {isGeneratingListing ? 'Generating...' : 'AI Optimize'}
                </Button>
              </div>
              <p className="text-xs text-muted-foreground mt-1">
                Title preferences (prefixes, suffixes, custom text) apply to all AI-generated titles.
              </p>
            </div>

            <div className="space-y-2">
              <div className="flex justify-between items-center">
                <Label htmlFor="title">Listing Title</Label>
                <span className={`text-xs ${listingData.title.length > 80 ? 'text-destructive font-medium' : listingData.title.length > 70 ? 'text-warning' : 'text-muted-foreground'}`}>
                  {listingData.title.length}/80 characters
                </span>
              </div>
              <Input
                id="title"
                value={listingData.title}
                onChange={(e) => setListingData({...listingData, title: e.target.value.slice(0, 80)})}
                placeholder="Enter listing title"
                required
                maxLength={80}
              />
              {listingData.category === 'magazine' && (
                <p className="text-xs text-muted-foreground">
                  Magazine titles start with "New" and include "Magazine" after the publication name.
                </p>
              )}
            </div>

            <div className="space-y-2">
              <Label htmlFor="price">Price ($)</Label>
              <Input
                id="price"
                type="number"
                step="0.01"
                value={listingData.price}
                onChange={(e) => setListingData({...listingData, price: e.target.value})}
                placeholder="0.00"
                required
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="condition">Condition</Label>
              <Select value={listingData.condition} onValueChange={(value) => setListingData({...listingData, condition: value})}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="new">New</SelectItem>
                  <SelectItem value="like-new">Like New</SelectItem>
                  <SelectItem value="good">Good</SelectItem>
                  <SelectItem value="fair">Fair</SelectItem>
                  <SelectItem value="poor">Poor</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label htmlFor="category">Category</Label>
              <Select value={listingData.category} onValueChange={(value) => setListingData({...listingData, category: value})}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="book">Book</SelectItem>
                  <SelectItem value="magazine">Magazine</SelectItem>
                  <SelectItem value="other">Other</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="grid grid-cols-2 gap-2">
              <div className="space-y-2">
                <Label htmlFor="genre">Genre</Label>
                <Input
                  id="genre"
                  value={listingData.genre}
                  onChange={(e) => setListingData({...listingData, genre: e.target.value})}
                  placeholder="e.g., Science Fiction"
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="topic">Topic</Label>
                <Input
                  id="topic"
                  value={listingData.topic}
                  onChange={(e) => setListingData({...listingData, topic: e.target.value})}
                  placeholder="e.g., AI, Cooking"
                />
              </div>
            </div>

            <div className="space-y-2">
              <Label htmlFor="description">Description</Label>
              <Textarea
                id="description"
                value={listingData.description}
                onChange={(e) => setListingData({...listingData, description: e.target.value})}
                placeholder="Describe the item condition, special features, etc."
                rows={4}
              />
            </div>

            <div className="flex gap-2 pt-4">
              <Button type="button" variant="outline" onClick={() => onOpenChange(false)} className="flex-1">
                Cancel
              </Button>
              <Button 
                type="submit" 
                className="flex-1" 
                disabled={isGeneratingListing || !user || ebayTokenValid === false}
              >
                {isGeneratingListing ? (
                  <>
                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                    Creating Listing...
                  </>
                ) : !user ? (
                  "Sign In Required"
                ) : ebayTokenValid === false ? (
                  "Connect eBay"
                ) : (
                  <>
                    <DollarSign className="w-4 h-4 mr-2" />
                    List on eBay
                  </>
                )}
              </Button>
            </div>
          </form>
        </div>
      </DialogContent>
      
      <TitlePreferencesModal 
        isOpen={showPreferences} 
        onClose={() => setShowPreferences(false)} 
      />
      
      <EbayAuthModal 
        isOpen={showEbayAuth} 
        onClose={() => setShowEbayAuth(false)}
        onAuthSuccess={() => {
          setShowEbayAuth(false);
          setEbayTokenValid(true);
          // Retry the listing generation after successful auth
          generateOptimizedListing();
        }}
      />
    </Dialog>
  );
}